---
resources:
- name: office_hours
  type: time
  source:
    interval: 2h
    start: 8:00 AM
    stop: 6:00 PM
    days: [Monday, Tuesday, Wednesday, Thursday, Friday]
    location: US/Pacific

- name: BuildBot
  type: git
  source:
    branch: master
    uri: https://github.com/Pivotal-DataFabric/BuildBot.git

jobs:
- name: BuildBotNotify
  max_in_flight: 1
  plan:
  - get: office_hours
    trigger: true
  - get: BuildBot
    trigger: true
  - task: run_build_bot
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ruby
          tag: '2.3'
      inputs:
      - name: BuildBot
      params:
        BASIC_AUTH_USERNAME: {{basic_auth_username}}
        BASIC_AUTH_PASSWORD: {{basic_auth_password}}
        SLACK_WEBHOOK_URL: {{slack_webhook_url}}
      run:
        path: "sh"
        args:
        - -exc
        - |
          cd BuildBot/
            bundle install
            ruby build_bot.rb
